#
# Copyright 2025 Calixto Systems
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += imx93_versa.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX93_LPDDR4X_1GB) += lpddr4x_1866mts_calixto_versa_IM8G16L4JCBG_1GB_timing.o
obj-$(CONFIG_IMX93_LPDDR4X_2GB) += lpddr4x_1866mts_calixto_versa_IMAG16L4JCDG_2GB_timing.o

endif
